// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { ParagraphPropertiesDB } from '../paragraphproperties-db'
import { ParagraphPropertiesService } from '../paragraphproperties.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-paragraphproperties-sorting',
  templateUrl: './paragraphproperties-sorting.component.html',
  styleUrls: ['./paragraphproperties-sorting.component.css']
})
export class ParagraphPropertiesSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of ParagraphProperties instances that are in the association
  associatedParagraphPropertiess = new Array<ParagraphPropertiesDB>();

  constructor(
    private paragraphpropertiesService: ParagraphPropertiesService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of paragraphproperties instances
    public dialogRef: MatDialogRef<ParagraphPropertiesSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getParagraphPropertiess()
  }

  getParagraphPropertiess(): void {
    this.frontRepoService.pull(this.dialogData.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let paragraphproperties of this.frontRepo.ParagraphPropertiess_array) {
          let ID = this.dialogData.ID
          let revPointerID = paragraphproperties[this.dialogData.ReversePointer as keyof ParagraphPropertiesDB] as unknown as NullInt64
          let revPointerID_Index = paragraphproperties[this.dialogData.ReversePointer + "_Index" as keyof ParagraphPropertiesDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedParagraphPropertiess.push(paragraphproperties)
          }
        }

        // sort associated paragraphproperties according to order
        this.associatedParagraphPropertiess.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedParagraphPropertiess, event.previousIndex, event.currentIndex);

    // set the order of ParagraphProperties instances
    let index = 0

    for (let paragraphproperties of this.associatedParagraphPropertiess) {
      let revPointerID_Index = paragraphproperties[this.dialogData.ReversePointer + "_Index" as keyof ParagraphPropertiesDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedParagraphPropertiess.forEach(
      paragraphproperties => {
        this.paragraphpropertiesService.updateParagraphProperties(paragraphproperties, this.dialogData.GONG__StackPath)
          .subscribe(paragraphproperties => {
            this.paragraphpropertiesService.ParagraphPropertiesServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer + ' done');
  }
}
