// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { RuneDB } from '../rune-db'
import { RuneService } from '../rune.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-rune-sorting',
  templateUrl: './rune-sorting.component.html',
  styleUrls: ['./rune-sorting.component.css']
})
export class RuneSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of Rune instances that are in the association
  associatedRunes = new Array<RuneDB>();

  constructor(
    private runeService: RuneService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of rune instances
    public dialogRef: MatDialogRef<RuneSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getRunes()
  }

  getRunes(): void {
    this.frontRepoService.pull(this.dialogData.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let rune of this.frontRepo.Runes_array) {
          let ID = this.dialogData.ID
          let revPointerID = rune[this.dialogData.ReversePointer as keyof RuneDB] as unknown as NullInt64
          let revPointerID_Index = rune[this.dialogData.ReversePointer + "_Index" as keyof RuneDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedRunes.push(rune)
          }
        }

        // sort associated rune according to order
        this.associatedRunes.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedRunes, event.previousIndex, event.currentIndex);

    // set the order of Rune instances
    let index = 0

    for (let rune of this.associatedRunes) {
      let revPointerID_Index = rune[this.dialogData.ReversePointer + "_Index" as keyof RuneDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedRunes.forEach(
      rune => {
        this.runeService.updateRune(rune, this.dialogData.GONG__StackPath)
          .subscribe(rune => {
            this.runeService.RuneServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer + ' done');
  }
}
