// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { RunePropertiesDB } from '../runeproperties-db'
import { RunePropertiesService } from '../runeproperties.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-runeproperties-sorting',
  templateUrl: './runeproperties-sorting.component.html',
  styleUrls: ['./runeproperties-sorting.component.css']
})
export class RunePropertiesSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of RuneProperties instances that are in the association
  associatedRunePropertiess = new Array<RunePropertiesDB>();

  constructor(
    private runepropertiesService: RunePropertiesService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of runeproperties instances
    public dialogRef: MatDialogRef<RunePropertiesSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getRunePropertiess()
  }

  getRunePropertiess(): void {
    this.frontRepoService.pull(this.dialogData.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let runeproperties of this.frontRepo.RunePropertiess_array) {
          let ID = this.dialogData.ID
          let revPointerID = runeproperties[this.dialogData.ReversePointer as keyof RunePropertiesDB] as unknown as NullInt64
          let revPointerID_Index = runeproperties[this.dialogData.ReversePointer + "_Index" as keyof RunePropertiesDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedRunePropertiess.push(runeproperties)
          }
        }

        // sort associated runeproperties according to order
        this.associatedRunePropertiess.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedRunePropertiess, event.previousIndex, event.currentIndex);

    // set the order of RuneProperties instances
    let index = 0

    for (let runeproperties of this.associatedRunePropertiess) {
      let revPointerID_Index = runeproperties[this.dialogData.ReversePointer + "_Index" as keyof RunePropertiesDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedRunePropertiess.forEach(
      runeproperties => {
        this.runepropertiesService.updateRuneProperties(runeproperties, this.dialogData.GONG__StackPath)
          .subscribe(runeproperties => {
            this.runepropertiesService.RunePropertiesServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer + ' done');
  }
}
