// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional, Input } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { ActivatedRoute, Router, RouterState } from '@angular/router';
import { TableColumnDB } from '../tablecolumn-db'
import { TableColumnService } from '../tablecolumn.service'

// insertion point for additional imports

import { RouteService } from '../route-service';

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-tablecolumnstable',
  templateUrl: './tablecolumns-table.component.html',
  styleUrls: ['./tablecolumns-table.component.css'],
})
export class TableColumnsTableComponent implements OnInit {

  @Input() GONG__StackPath: string = ""

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of TableColumn instances
  selection: SelectionModel<TableColumnDB> = new (SelectionModel)
  initialSelection = new Array<TableColumnDB>()

  // the data source for the table
  tablecolumns: TableColumnDB[] = []
  matTableDataSource: MatTableDataSource<TableColumnDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.tablecolumns
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (tablecolumnDB: TableColumnDB, property: string) => {
      switch (property) {
        case 'ID':
          return tablecolumnDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return tablecolumnDB.Name;

        case 'Content':
          return tablecolumnDB.Content;

        case 'Node':
          return (tablecolumnDB.Node ? tablecolumnDB.Node.Name : '');

        case 'TableRow_TableColumns':
          if (this.frontRepo.TableRows.get(tablecolumnDB.TableRow_TableColumnsDBID.Int64) != undefined) {
            return this.frontRepo.TableRows.get(tablecolumnDB.TableRow_TableColumnsDBID.Int64)!.Name
          } else {
            return ""
          }

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (tablecolumnDB: TableColumnDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the tablecolumnDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += tablecolumnDB.Name.toLowerCase()
      mergedContent += tablecolumnDB.Content.toLowerCase()
      if (tablecolumnDB.Node) {
        mergedContent += tablecolumnDB.Node.Name.toLowerCase()
      }
      if (tablecolumnDB.TableRow_TableColumnsDBID.Int64 != 0) {
        mergedContent += this.frontRepo.TableRows.get(tablecolumnDB.TableRow_TableColumnsDBID.Int64)!.Name.toLowerCase()
      }


      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private tablecolumnService: TableColumnService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of tablecolumn instances
    public dialogRef: MatDialogRef<TableColumnsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
    private activatedRoute: ActivatedRoute,

    private routeService: RouteService,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      this.GONG__StackPath = dialogData.GONG__StackPath
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.tablecolumnService.TableColumnServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getTableColumns()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Delete', // insertion point for columns to display
        "Name",
        "Content",
        "Node",
        "TableRow_TableColumns",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Content",
        "Node",
        "TableRow_TableColumns",
      ]
      this.selection = new SelectionModel<TableColumnDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    let stackPath = this.activatedRoute.snapshot.paramMap.get('GONG__StackPath')
    if (stackPath != undefined) {
      this.GONG__StackPath = stackPath
    }

    this.getTableColumns()

    this.matTableDataSource = new MatTableDataSource(this.tablecolumns)
  }

  getTableColumns(): void {
    this.frontRepoService.pull(this.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.tablecolumns = this.frontRepo.TableColumns_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let tablecolumn of this.tablecolumns) {
            let ID = this.dialogData.ID
            let revPointer = tablecolumn[this.dialogData.ReversePointer as keyof TableColumnDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(tablecolumn)
            }
            this.selection = new SelectionModel<TableColumnDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, TableColumnDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          // we associates on sourceInstance of type SourceStruct with a MANY MANY associations to TableColumnDB
          // the field name is sourceField
          let sourceFieldArray = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as TableColumnDB[]
          if (sourceFieldArray != null) {
            for (let associationInstance of sourceFieldArray) {
              let tablecolumn = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as TableColumnDB
              this.initialSelection.push(tablecolumn)
            }
          }

          this.selection = new SelectionModel<TableColumnDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.tablecolumns
      }
    )
  }

  // newTableColumn initiate a new tablecolumn
  // create a new TableColumn objet
  newTableColumn() {
  }

  deleteTableColumn(tablecolumnID: number, tablecolumn: TableColumnDB) {
    // list of tablecolumns is truncated of tablecolumn before the delete
    this.tablecolumns = this.tablecolumns.filter(h => h !== tablecolumn);

    this.tablecolumnService.deleteTableColumn(tablecolumnID, this.GONG__StackPath).subscribe(
      tablecolumn => {
        this.tablecolumnService.TableColumnServiceChanged.next("delete")
      }
    );
  }

  editTableColumn(tablecolumnID: number, tablecolumn: TableColumnDB) {

  }

  // set editor outlet
  setEditorRouterOutlet(tablecolumnID: number) {
    let outletName = this.routeService.getEditorOutlet(this.GONG__StackPath)
    let fullPath = this.routeService.getPathRoot() + "-" + "tablecolumn" + "-detail"

    let outletConf: any = {}
    outletConf[outletName] = [fullPath, tablecolumnID, this.GONG__StackPath]

    this.router.navigate([{ outlets: outletConf }])
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.tablecolumns.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.tablecolumns.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<TableColumnDB>()

      // reset all initial selection of tablecolumn that belong to tablecolumn
      for (let tablecolumn of this.initialSelection) {
        let index = tablecolumn[this.dialogData.ReversePointer as keyof TableColumnDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(tablecolumn)

      }

      // from selection, set tablecolumn that belong to tablecolumn
      for (let tablecolumn of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = tablecolumn[this.dialogData.ReversePointer as keyof TableColumnDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(tablecolumn)
      }


      // update all tablecolumn (only update selection & initial selection)
      for (let tablecolumn of toUpdate) {
        this.tablecolumnService.updateTableColumn(tablecolumn, this.GONG__StackPath)
          .subscribe(tablecolumn => {
            this.tablecolumnService.TableColumnServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, TableColumnDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedTableColumn = new Set<number>()
      for (let tablecolumn of this.initialSelection) {
        if (this.selection.selected.includes(tablecolumn)) {
          // console.log("tablecolumn " + tablecolumn.Name + " is still selected")
        } else {
          console.log("tablecolumn " + tablecolumn.Name + " has been unselected")
          unselectedTableColumn.add(tablecolumn.ID)
          console.log("is unselected " + unselectedTableColumn.has(tablecolumn.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let tablecolumn = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as TableColumnDB
      if (unselectedTableColumn.has(tablecolumn.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<TableColumnDB>) = new Array<TableColumnDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          tablecolumn => {
            if (!this.initialSelection.includes(tablecolumn)) {
              // console.log("tablecolumn " + tablecolumn.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + tablecolumn.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = tablecolumn.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = tablecolumn.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("tablecolumn " + tablecolumn.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<TableColumnDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
