// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { FileDB } from '../file-db'
import { FileService } from '../file.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-file-sorting',
  templateUrl: './file-sorting.component.html',
  styleUrls: ['./file-sorting.component.css']
})
export class FileSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of File instances that are in the association
  associatedFiles = new Array<FileDB>();

  constructor(
    private fileService: FileService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of file instances
    public dialogRef: MatDialogRef<FileSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getFiles()
  }

  getFiles(): void {
    this.frontRepoService.pull(this.dialogData.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let file of this.frontRepo.Files_array) {
          let ID = this.dialogData.ID
          let revPointerID = file[this.dialogData.ReversePointer as keyof FileDB] as unknown as NullInt64
          let revPointerID_Index = file[this.dialogData.ReversePointer + "_Index" as keyof FileDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedFiles.push(file)
          }
        }

        // sort associated file according to order
        this.associatedFiles.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedFiles, event.previousIndex, event.currentIndex);

    // set the order of File instances
    let index = 0

    for (let file of this.associatedFiles) {
      let revPointerID_Index = file[this.dialogData.ReversePointer + "_Index" as keyof FileDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedFiles.forEach(
      file => {
        this.fileService.updateFile(file, this.dialogData.GONG__StackPath)
          .subscribe(file => {
            this.fileService.FileServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer + ' done');
  }
}
