// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { DocumentDB } from './document-db';

// insertion point for imports
import { FileDB } from './file-db'
import { NodeDB } from './node-db'
import { BodyDB } from './body-db'

@Injectable({
  providedIn: 'root'
})
export class DocumentService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  DocumentServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private documentsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.documentsUrl = origin + '/api/github.com/fullstack-lang/gongdocx/go/v1/documents';
  }

  /** GET documents from the server */
  getDocuments(GONG__StackPath: string): Observable<DocumentDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<DocumentDB[]>(this.documentsUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched documents')),
        catchError(this.handleError<DocumentDB[]>('getDocuments', []))
      );
  }

  /** GET document by id. Will 404 if id not found */
  getDocument(id: number, GONG__StackPath: string): Observable<DocumentDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.documentsUrl}/${id}`;
    return this.http.get<DocumentDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched document id=${id}`)),
      catchError(this.handleError<DocumentDB>(`getDocument id=${id}`))
    );
  }

  /** POST: add a new document to the server */
  postDocument(documentdb: DocumentDB, GONG__StackPath: string): Observable<DocumentDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    documentdb.File = new FileDB
    documentdb.Root = new NodeDB
    documentdb.Body = new BodyDB

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<DocumentDB>(this.documentsUrl, documentdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`posted documentdb id=${documentdb.ID}`)
      }),
      catchError(this.handleError<DocumentDB>('postDocument'))
    );
  }

  /** DELETE: delete the documentdb from the server */
  deleteDocument(documentdb: DocumentDB | number, GONG__StackPath: string): Observable<DocumentDB> {
    const id = typeof documentdb === 'number' ? documentdb : documentdb.ID;
    const url = `${this.documentsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<DocumentDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted documentdb id=${id}`)),
      catchError(this.handleError<DocumentDB>('deleteDocument'))
    );
  }

  /** PUT: update the documentdb on the server */
  updateDocument(documentdb: DocumentDB, GONG__StackPath: string): Observable<DocumentDB> {
    const id = typeof documentdb === 'number' ? documentdb : documentdb.ID;
    const url = `${this.documentsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    documentdb.File = new FileDB
    documentdb.Root = new NodeDB
    documentdb.Body = new BodyDB

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<DocumentDB>(url, documentdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`updated documentdb id=${documentdb.ID}`)
      }),
      catchError(this.handleError<DocumentDB>('updateDocument'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in DocumentService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("DocumentService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
