// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { ParagraphDB } from './paragraph-db';

// insertion point for imports
import { NodeDB } from './node-db'
import { ParagraphPropertiesDB } from './paragraphproperties-db'
import { BodyDB } from './body-db'
import { TableColumnDB } from './tablecolumn-db'

@Injectable({
  providedIn: 'root'
})
export class ParagraphService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  ParagraphServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private paragraphsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.paragraphsUrl = origin + '/api/github.com/fullstack-lang/gongdocx/go/v1/paragraphs';
  }

  /** GET paragraphs from the server */
  getParagraphs(GONG__StackPath: string): Observable<ParagraphDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<ParagraphDB[]>(this.paragraphsUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched paragraphs')),
        catchError(this.handleError<ParagraphDB[]>('getParagraphs', []))
      );
  }

  /** GET paragraph by id. Will 404 if id not found */
  getParagraph(id: number, GONG__StackPath: string): Observable<ParagraphDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.paragraphsUrl}/${id}`;
    return this.http.get<ParagraphDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched paragraph id=${id}`)),
      catchError(this.handleError<ParagraphDB>(`getParagraph id=${id}`))
    );
  }

  /** POST: add a new paragraph to the server */
  postParagraph(paragraphdb: ParagraphDB, GONG__StackPath: string): Observable<ParagraphDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    paragraphdb.Node = new NodeDB
    paragraphdb.ParagraphProperties = new ParagraphPropertiesDB
    paragraphdb.Runes = []
    paragraphdb.Next = new ParagraphDB
    paragraphdb.Previous = new ParagraphDB
    let _Body_Paragraphs_reverse = paragraphdb.Body_Paragraphs_reverse
    paragraphdb.Body_Paragraphs_reverse = new BodyDB
    let _TableColumn_Paragraphs_reverse = paragraphdb.TableColumn_Paragraphs_reverse
    paragraphdb.TableColumn_Paragraphs_reverse = new TableColumnDB

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<ParagraphDB>(this.paragraphsUrl, paragraphdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        paragraphdb.Body_Paragraphs_reverse = _Body_Paragraphs_reverse
        paragraphdb.TableColumn_Paragraphs_reverse = _TableColumn_Paragraphs_reverse
        // this.log(`posted paragraphdb id=${paragraphdb.ID}`)
      }),
      catchError(this.handleError<ParagraphDB>('postParagraph'))
    );
  }

  /** DELETE: delete the paragraphdb from the server */
  deleteParagraph(paragraphdb: ParagraphDB | number, GONG__StackPath: string): Observable<ParagraphDB> {
    const id = typeof paragraphdb === 'number' ? paragraphdb : paragraphdb.ID;
    const url = `${this.paragraphsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<ParagraphDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted paragraphdb id=${id}`)),
      catchError(this.handleError<ParagraphDB>('deleteParagraph'))
    );
  }

  /** PUT: update the paragraphdb on the server */
  updateParagraph(paragraphdb: ParagraphDB, GONG__StackPath: string): Observable<ParagraphDB> {
    const id = typeof paragraphdb === 'number' ? paragraphdb : paragraphdb.ID;
    const url = `${this.paragraphsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    paragraphdb.Node = new NodeDB
    paragraphdb.ParagraphProperties = new ParagraphPropertiesDB
    paragraphdb.Runes = []
    paragraphdb.Next = new ParagraphDB
    paragraphdb.Previous = new ParagraphDB
    let _Body_Paragraphs_reverse = paragraphdb.Body_Paragraphs_reverse
    paragraphdb.Body_Paragraphs_reverse = new BodyDB
    let _TableColumn_Paragraphs_reverse = paragraphdb.TableColumn_Paragraphs_reverse
    paragraphdb.TableColumn_Paragraphs_reverse = new TableColumnDB

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<ParagraphDB>(url, paragraphdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        paragraphdb.Body_Paragraphs_reverse = _Body_Paragraphs_reverse
        paragraphdb.TableColumn_Paragraphs_reverse = _TableColumn_Paragraphs_reverse
        // this.log(`updated paragraphdb id=${paragraphdb.ID}`)
      }),
      catchError(this.handleError<ParagraphDB>('updateParagraph'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in ParagraphService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("ParagraphService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
