// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { ParagraphStyleDB } from './paragraphstyle-db';

// insertion point for imports
import { NodeDB } from './node-db'

@Injectable({
  providedIn: 'root'
})
export class ParagraphStyleService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  ParagraphStyleServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private paragraphstylesUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.paragraphstylesUrl = origin + '/api/github.com/fullstack-lang/gongdocx/go/v1/paragraphstyles';
  }

  /** GET paragraphstyles from the server */
  getParagraphStyles(GONG__StackPath: string): Observable<ParagraphStyleDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<ParagraphStyleDB[]>(this.paragraphstylesUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched paragraphstyles')),
        catchError(this.handleError<ParagraphStyleDB[]>('getParagraphStyles', []))
      );
  }

  /** GET paragraphstyle by id. Will 404 if id not found */
  getParagraphStyle(id: number, GONG__StackPath: string): Observable<ParagraphStyleDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.paragraphstylesUrl}/${id}`;
    return this.http.get<ParagraphStyleDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched paragraphstyle id=${id}`)),
      catchError(this.handleError<ParagraphStyleDB>(`getParagraphStyle id=${id}`))
    );
  }

  /** POST: add a new paragraphstyle to the server */
  postParagraphStyle(paragraphstyledb: ParagraphStyleDB, GONG__StackPath: string): Observable<ParagraphStyleDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    paragraphstyledb.Node = new NodeDB

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<ParagraphStyleDB>(this.paragraphstylesUrl, paragraphstyledb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`posted paragraphstyledb id=${paragraphstyledb.ID}`)
      }),
      catchError(this.handleError<ParagraphStyleDB>('postParagraphStyle'))
    );
  }

  /** DELETE: delete the paragraphstyledb from the server */
  deleteParagraphStyle(paragraphstyledb: ParagraphStyleDB | number, GONG__StackPath: string): Observable<ParagraphStyleDB> {
    const id = typeof paragraphstyledb === 'number' ? paragraphstyledb : paragraphstyledb.ID;
    const url = `${this.paragraphstylesUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<ParagraphStyleDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted paragraphstyledb id=${id}`)),
      catchError(this.handleError<ParagraphStyleDB>('deleteParagraphStyle'))
    );
  }

  /** PUT: update the paragraphstyledb on the server */
  updateParagraphStyle(paragraphstyledb: ParagraphStyleDB, GONG__StackPath: string): Observable<ParagraphStyleDB> {
    const id = typeof paragraphstyledb === 'number' ? paragraphstyledb : paragraphstyledb.ID;
    const url = `${this.paragraphstylesUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    paragraphstyledb.Node = new NodeDB

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<ParagraphStyleDB>(url, paragraphstyledb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`updated paragraphstyledb id=${paragraphstyledb.ID}`)
      }),
      catchError(this.handleError<ParagraphStyleDB>('updateParagraphStyle'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in ParagraphStyleService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("ParagraphStyleService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
