// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { TableRowDB } from './tablerow-db';

// insertion point for imports
import { NodeDB } from './node-db'
import { TableDB } from './table-db'

@Injectable({
  providedIn: 'root'
})
export class TableRowService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  TableRowServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private tablerowsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.tablerowsUrl = origin + '/api/github.com/fullstack-lang/gongdocx/go/v1/tablerows';
  }

  /** GET tablerows from the server */
  getTableRows(GONG__StackPath: string): Observable<TableRowDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<TableRowDB[]>(this.tablerowsUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched tablerows')),
        catchError(this.handleError<TableRowDB[]>('getTableRows', []))
      );
  }

  /** GET tablerow by id. Will 404 if id not found */
  getTableRow(id: number, GONG__StackPath: string): Observable<TableRowDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.tablerowsUrl}/${id}`;
    return this.http.get<TableRowDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched tablerow id=${id}`)),
      catchError(this.handleError<TableRowDB>(`getTableRow id=${id}`))
    );
  }

  /** POST: add a new tablerow to the server */
  postTableRow(tablerowdb: TableRowDB, GONG__StackPath: string): Observable<TableRowDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    tablerowdb.Node = new NodeDB
    tablerowdb.TableColumns = []
    let _Table_TableRows_reverse = tablerowdb.Table_TableRows_reverse
    tablerowdb.Table_TableRows_reverse = new TableDB

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<TableRowDB>(this.tablerowsUrl, tablerowdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        tablerowdb.Table_TableRows_reverse = _Table_TableRows_reverse
        // this.log(`posted tablerowdb id=${tablerowdb.ID}`)
      }),
      catchError(this.handleError<TableRowDB>('postTableRow'))
    );
  }

  /** DELETE: delete the tablerowdb from the server */
  deleteTableRow(tablerowdb: TableRowDB | number, GONG__StackPath: string): Observable<TableRowDB> {
    const id = typeof tablerowdb === 'number' ? tablerowdb : tablerowdb.ID;
    const url = `${this.tablerowsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<TableRowDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted tablerowdb id=${id}`)),
      catchError(this.handleError<TableRowDB>('deleteTableRow'))
    );
  }

  /** PUT: update the tablerowdb on the server */
  updateTableRow(tablerowdb: TableRowDB, GONG__StackPath: string): Observable<TableRowDB> {
    const id = typeof tablerowdb === 'number' ? tablerowdb : tablerowdb.ID;
    const url = `${this.tablerowsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    tablerowdb.Node = new NodeDB
    tablerowdb.TableColumns = []
    let _Table_TableRows_reverse = tablerowdb.Table_TableRows_reverse
    tablerowdb.Table_TableRows_reverse = new TableDB

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<TableRowDB>(url, tablerowdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        tablerowdb.Table_TableRows_reverse = _Table_TableRows_reverse
        // this.log(`updated tablerowdb id=${tablerowdb.ID}`)
      }),
      catchError(this.handleError<TableRowDB>('updateTableRow'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in TableRowService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("TableRowService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
