// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional, Input } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { ActivatedRoute, Router, RouterState } from '@angular/router';
import { BodyDB } from '../body-db'
import { BodyService } from '../body.service'

// insertion point for additional imports

import { RouteService } from '../route-service';

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-bodystable',
  templateUrl: './bodys-table.component.html',
  styleUrls: ['./bodys-table.component.css'],
})
export class BodysTableComponent implements OnInit {

  @Input() GONG__StackPath: string = ""

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of Body instances
  selection: SelectionModel<BodyDB> = new (SelectionModel)
  initialSelection = new Array<BodyDB>()

  // the data source for the table
  bodys: BodyDB[] = []
  matTableDataSource: MatTableDataSource<BodyDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.bodys
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (bodyDB: BodyDB, property: string) => {
      switch (property) {
        case 'ID':
          return bodyDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return bodyDB.Name;

        case 'LastParagraph':
          return (bodyDB.LastParagraph ? bodyDB.LastParagraph.Name : '');

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (bodyDB: BodyDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the bodyDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += bodyDB.Name.toLowerCase()
      if (bodyDB.LastParagraph) {
        mergedContent += bodyDB.LastParagraph.Name.toLowerCase()
      }

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private bodyService: BodyService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of body instances
    public dialogRef: MatDialogRef<BodysTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
    private activatedRoute: ActivatedRoute,

    private routeService: RouteService,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      this.GONG__StackPath = dialogData.GONG__StackPath
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.bodyService.BodyServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getBodys()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Delete', // insertion point for columns to display
        "Name",
        "LastParagraph",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "LastParagraph",
      ]
      this.selection = new SelectionModel<BodyDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    let stackPath = this.activatedRoute.snapshot.paramMap.get('GONG__StackPath')
    if (stackPath != undefined) {
      this.GONG__StackPath = stackPath
    }

    this.getBodys()

    this.matTableDataSource = new MatTableDataSource(this.bodys)
  }

  getBodys(): void {
    this.frontRepoService.pull(this.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.bodys = this.frontRepo.Bodys_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let body of this.bodys) {
            let ID = this.dialogData.ID
            let revPointer = body[this.dialogData.ReversePointer as keyof BodyDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(body)
            }
            this.selection = new SelectionModel<BodyDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, BodyDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          // we associates on sourceInstance of type SourceStruct with a MANY MANY associations to BodyDB
          // the field name is sourceField
          let sourceFieldArray = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as BodyDB[]
          if (sourceFieldArray != null) {
            for (let associationInstance of sourceFieldArray) {
              let body = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as BodyDB
              this.initialSelection.push(body)
            }
          }

          this.selection = new SelectionModel<BodyDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.bodys
      }
    )
  }

  // newBody initiate a new body
  // create a new Body objet
  newBody() {
  }

  deleteBody(bodyID: number, body: BodyDB) {
    // list of bodys is truncated of body before the delete
    this.bodys = this.bodys.filter(h => h !== body);

    this.bodyService.deleteBody(bodyID, this.GONG__StackPath).subscribe(
      body => {
        this.bodyService.BodyServiceChanged.next("delete")
      }
    );
  }

  editBody(bodyID: number, body: BodyDB) {

  }

  // set editor outlet
  setEditorRouterOutlet(bodyID: number) {
    let outletName = this.routeService.getEditorOutlet(this.GONG__StackPath)
    let fullPath = this.routeService.getPathRoot() + "-" + "body" + "-detail"

    let outletConf: any = {}
    outletConf[outletName] = [fullPath, bodyID, this.GONG__StackPath]

    this.router.navigate([{ outlets: outletConf }])
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.bodys.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.bodys.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<BodyDB>()

      // reset all initial selection of body that belong to body
      for (let body of this.initialSelection) {
        let index = body[this.dialogData.ReversePointer as keyof BodyDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(body)

      }

      // from selection, set body that belong to body
      for (let body of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = body[this.dialogData.ReversePointer as keyof BodyDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(body)
      }


      // update all body (only update selection & initial selection)
      for (let body of toUpdate) {
        this.bodyService.updateBody(body, this.GONG__StackPath)
          .subscribe(body => {
            this.bodyService.BodyServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, BodyDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedBody = new Set<number>()
      for (let body of this.initialSelection) {
        if (this.selection.selected.includes(body)) {
          // console.log("body " + body.Name + " is still selected")
        } else {
          console.log("body " + body.Name + " has been unselected")
          unselectedBody.add(body.ID)
          console.log("is unselected " + unselectedBody.has(body.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let body = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as BodyDB
      if (unselectedBody.has(body.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<BodyDB>) = new Array<BodyDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          body => {
            if (!this.initialSelection.includes(body)) {
              // console.log("body " + body.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + body.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = body.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = body.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("body " + body.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<BodyDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
