// generated by stacks/gong/go/models/orm_file_per_struct_back_repo.go
package orm

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"sort"
	"time"

	"gorm.io/gorm"

	"github.com/tealeg/xlsx/v3"

	"github.com/fullstack-lang/gongdocx/go/models"
)

// dummy variable to have the import declaration wihthout compile failure (even if no code needing this import is generated)
var dummy_Text_sql sql.NullBool
var dummy_Text_time time.Duration
var dummy_Text_sort sort.Float64Slice

// TextAPI is the input in POST API
//
// for POST, API, one needs the fields of the model as well as the fields
// from associations ("Has One" and "Has Many") that are generated to
// fullfill the ORM requirements for associations
//
// swagger:model textAPI
type TextAPI struct {
	gorm.Model

	models.Text

	// encoding of pointers
	TextPointersEnconding
}

// TextPointersEnconding encodes pointers to Struct and
// reverse pointers of slice of poitners to Struct
type TextPointersEnconding struct {
	// insertion for pointer fields encoding declaration

	// field Node is a pointer to another Struct (optional or 0..1)
	// This field is generated into another field to enable AS ONE association
	NodeID sql.NullInt64

	// field EnclosingRune is a pointer to another Struct (optional or 0..1)
	// This field is generated into another field to enable AS ONE association
	EnclosingRuneID sql.NullInt64
}

// TextDB describes a text in the database
//
// It incorporates the GORM ID, basic fields from the model (because they can be serialized),
// the encoded version of pointers
//
// swagger:model textDB
type TextDB struct {
	gorm.Model

	// insertion for basic fields declaration

	// Declation for basic field textDB.Name
	Name_Data sql.NullString

	// Declation for basic field textDB.Content
	Content_Data sql.NullString

	// Declation for basic field textDB.PreserveWhiteSpace
	// provide the sql storage for the boolan
	PreserveWhiteSpace_Data sql.NullBool
	// encoding of pointers
	TextPointersEnconding
}

// TextDBs arrays textDBs
// swagger:response textDBsResponse
type TextDBs []TextDB

// TextDBResponse provides response
// swagger:response textDBResponse
type TextDBResponse struct {
	TextDB
}

// TextWOP is a Text without pointers (WOP is an acronym for "Without Pointers")
// it holds the same basic fields but pointers are encoded into uint
type TextWOP struct {
	ID int `xlsx:"0"`

	// insertion for WOP basic fields

	Name string `xlsx:"1"`

	Content string `xlsx:"2"`

	PreserveWhiteSpace bool `xlsx:"3"`
	// insertion for WOP pointer fields
}

var Text_Fields = []string{
	// insertion for WOP basic fields
	"ID",
	"Name",
	"Content",
	"PreserveWhiteSpace",
}

type BackRepoTextStruct struct {
	// stores TextDB according to their gorm ID
	Map_TextDBID_TextDB map[uint]*TextDB

	// stores TextDB ID according to Text address
	Map_TextPtr_TextDBID map[*models.Text]uint

	// stores Text according to their gorm ID
	Map_TextDBID_TextPtr map[uint]*models.Text

	db *gorm.DB

	stage *models.StageStruct
}

func (backRepoText *BackRepoTextStruct) GetStage() (stage *models.StageStruct) {
	stage = backRepoText.stage
	return
}

func (backRepoText *BackRepoTextStruct) GetDB() *gorm.DB {
	return backRepoText.db
}

// GetTextDBFromTextPtr is a handy function to access the back repo instance from the stage instance
func (backRepoText *BackRepoTextStruct) GetTextDBFromTextPtr(text *models.Text) (textDB *TextDB) {
	id := backRepoText.Map_TextPtr_TextDBID[text]
	textDB = backRepoText.Map_TextDBID_TextDB[id]
	return
}

// BackRepoText.CommitPhaseOne commits all staged instances of Text to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoText *BackRepoTextStruct) CommitPhaseOne(stage *models.StageStruct) (Error error) {

	for text := range stage.Texts {
		backRepoText.CommitPhaseOneInstance(text)
	}

	// parse all backRepo instance and checks wether some instance have been unstaged
	// in this case, remove them from the back repo
	for id, text := range backRepoText.Map_TextDBID_TextPtr {
		if _, ok := stage.Texts[text]; !ok {
			backRepoText.CommitDeleteInstance(id)
		}
	}

	return
}

// BackRepoText.CommitDeleteInstance commits deletion of Text to the BackRepo
func (backRepoText *BackRepoTextStruct) CommitDeleteInstance(id uint) (Error error) {

	text := backRepoText.Map_TextDBID_TextPtr[id]

	// text is not staged anymore, remove textDB
	textDB := backRepoText.Map_TextDBID_TextDB[id]
	query := backRepoText.db.Unscoped().Delete(&textDB)
	if query.Error != nil {
		return query.Error
	}

	// update stores
	delete(backRepoText.Map_TextPtr_TextDBID, text)
	delete(backRepoText.Map_TextDBID_TextPtr, id)
	delete(backRepoText.Map_TextDBID_TextDB, id)

	return
}

// BackRepoText.CommitPhaseOneInstance commits text staged instances of Text to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoText *BackRepoTextStruct) CommitPhaseOneInstance(text *models.Text) (Error error) {

	// check if the text is not commited yet
	if _, ok := backRepoText.Map_TextPtr_TextDBID[text]; ok {
		return
	}

	// initiate text
	var textDB TextDB
	textDB.CopyBasicFieldsFromText(text)

	query := backRepoText.db.Create(&textDB)
	if query.Error != nil {
		return query.Error
	}

	// update stores
	backRepoText.Map_TextPtr_TextDBID[text] = textDB.ID
	backRepoText.Map_TextDBID_TextPtr[textDB.ID] = text
	backRepoText.Map_TextDBID_TextDB[textDB.ID] = &textDB

	return
}

// BackRepoText.CommitPhaseTwo commits all staged instances of Text to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoText *BackRepoTextStruct) CommitPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	for idx, text := range backRepoText.Map_TextDBID_TextPtr {
		backRepoText.CommitPhaseTwoInstance(backRepo, idx, text)
	}

	return
}

// BackRepoText.CommitPhaseTwoInstance commits {{structname }} of models.Text to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoText *BackRepoTextStruct) CommitPhaseTwoInstance(backRepo *BackRepoStruct, idx uint, text *models.Text) (Error error) {

	// fetch matching textDB
	if textDB, ok := backRepoText.Map_TextDBID_TextDB[idx]; ok {

		textDB.CopyBasicFieldsFromText(text)

		// insertion point for translating pointers encodings into actual pointers
		// commit pointer value text.Node translates to updating the text.NodeID
		textDB.NodeID.Valid = true // allow for a 0 value (nil association)
		if text.Node != nil {
			if NodeId, ok := backRepo.BackRepoNode.Map_NodePtr_NodeDBID[text.Node]; ok {
				textDB.NodeID.Int64 = int64(NodeId)
				textDB.NodeID.Valid = true
			}
		} else {
			textDB.NodeID.Int64 = 0
			textDB.NodeID.Valid = true
		}

		// commit pointer value text.EnclosingRune translates to updating the text.EnclosingRuneID
		textDB.EnclosingRuneID.Valid = true // allow for a 0 value (nil association)
		if text.EnclosingRune != nil {
			if EnclosingRuneId, ok := backRepo.BackRepoRune.Map_RunePtr_RuneDBID[text.EnclosingRune]; ok {
				textDB.EnclosingRuneID.Int64 = int64(EnclosingRuneId)
				textDB.EnclosingRuneID.Valid = true
			}
		} else {
			textDB.EnclosingRuneID.Int64 = 0
			textDB.EnclosingRuneID.Valid = true
		}

		query := backRepoText.db.Save(&textDB)
		if query.Error != nil {
			return query.Error
		}

	} else {
		err := errors.New(
			fmt.Sprintf("Unkown Text intance %s", text.Name))
		return err
	}

	return
}

// BackRepoText.CheckoutPhaseOne Checkouts all BackRepo instances to the Stage
//
// Phase One will result in having instances on the stage aligned with the back repo
// pointers are not initialized yet (this is for phase two)
func (backRepoText *BackRepoTextStruct) CheckoutPhaseOne() (Error error) {

	textDBArray := make([]TextDB, 0)
	query := backRepoText.db.Find(&textDBArray)
	if query.Error != nil {
		return query.Error
	}

	// list of instances to be removed
	// start from the initial map on the stage and remove instances that have been checked out
	textInstancesToBeRemovedFromTheStage := make(map[*models.Text]any)
	for key, value := range backRepoText.stage.Texts {
		textInstancesToBeRemovedFromTheStage[key] = value
	}

	// copy orm objects to the the map
	for _, textDB := range textDBArray {
		backRepoText.CheckoutPhaseOneInstance(&textDB)

		// do not remove this instance from the stage, therefore
		// remove instance from the list of instances to be be removed from the stage
		text, ok := backRepoText.Map_TextDBID_TextPtr[textDB.ID]
		if ok {
			delete(textInstancesToBeRemovedFromTheStage, text)
		}
	}

	// remove from stage and back repo's 3 maps all texts that are not in the checkout
	for text := range textInstancesToBeRemovedFromTheStage {
		text.Unstage(backRepoText.GetStage())

		// remove instance from the back repo 3 maps
		textID := backRepoText.Map_TextPtr_TextDBID[text]
		delete(backRepoText.Map_TextPtr_TextDBID, text)
		delete(backRepoText.Map_TextDBID_TextDB, textID)
		delete(backRepoText.Map_TextDBID_TextPtr, textID)
	}

	return
}

// CheckoutPhaseOneInstance takes a textDB that has been found in the DB, updates the backRepo and stages the
// models version of the textDB
func (backRepoText *BackRepoTextStruct) CheckoutPhaseOneInstance(textDB *TextDB) (Error error) {

	text, ok := backRepoText.Map_TextDBID_TextPtr[textDB.ID]
	if !ok {
		text = new(models.Text)

		backRepoText.Map_TextDBID_TextPtr[textDB.ID] = text
		backRepoText.Map_TextPtr_TextDBID[text] = textDB.ID

		// append model store with the new element
		text.Name = textDB.Name_Data.String
		text.Stage(backRepoText.GetStage())
	}
	textDB.CopyBasicFieldsToText(text)

	// in some cases, the instance might have been unstaged. It is necessary to stage it again
	text.Stage(backRepoText.GetStage())

	// preserve pointer to textDB. Otherwise, pointer will is recycled and the map of pointers
	// Map_TextDBID_TextDB)[textDB hold variable pointers
	textDB_Data := *textDB
	preservedPtrToText := &textDB_Data
	backRepoText.Map_TextDBID_TextDB[textDB.ID] = preservedPtrToText

	return
}

// BackRepoText.CheckoutPhaseTwo Checkouts all staged instances of Text to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoText *BackRepoTextStruct) CheckoutPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	// parse all DB instance and update all pointer fields of the translated models instance
	for _, textDB := range backRepoText.Map_TextDBID_TextDB {
		backRepoText.CheckoutPhaseTwoInstance(backRepo, textDB)
	}
	return
}

// BackRepoText.CheckoutPhaseTwoInstance Checkouts staged instances of Text to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoText *BackRepoTextStruct) CheckoutPhaseTwoInstance(backRepo *BackRepoStruct, textDB *TextDB) (Error error) {

	text := backRepoText.Map_TextDBID_TextPtr[textDB.ID]
	_ = text // sometimes, there is no code generated. This lines voids the "unused variable" compilation error

	// insertion point for checkout of pointer encoding
	// Node field
	text.Node = nil
	if textDB.NodeID.Int64 != 0 {
		text.Node = backRepo.BackRepoNode.Map_NodeDBID_NodePtr[uint(textDB.NodeID.Int64)]
	}
	// EnclosingRune field
	text.EnclosingRune = nil
	if textDB.EnclosingRuneID.Int64 != 0 {
		text.EnclosingRune = backRepo.BackRepoRune.Map_RuneDBID_RunePtr[uint(textDB.EnclosingRuneID.Int64)]
	}
	return
}

// CommitText allows commit of a single text (if already staged)
func (backRepo *BackRepoStruct) CommitText(text *models.Text) {
	backRepo.BackRepoText.CommitPhaseOneInstance(text)
	if id, ok := backRepo.BackRepoText.Map_TextPtr_TextDBID[text]; ok {
		backRepo.BackRepoText.CommitPhaseTwoInstance(backRepo, id, text)
	}
	backRepo.CommitFromBackNb = backRepo.CommitFromBackNb + 1
}

// CommitText allows checkout of a single text (if already staged and with a BackRepo id)
func (backRepo *BackRepoStruct) CheckoutText(text *models.Text) {
	// check if the text is staged
	if _, ok := backRepo.BackRepoText.Map_TextPtr_TextDBID[text]; ok {

		if id, ok := backRepo.BackRepoText.Map_TextPtr_TextDBID[text]; ok {
			var textDB TextDB
			textDB.ID = id

			if err := backRepo.BackRepoText.db.First(&textDB, id).Error; err != nil {
				log.Panicln("CheckoutText : Problem with getting object with id:", id)
			}
			backRepo.BackRepoText.CheckoutPhaseOneInstance(&textDB)
			backRepo.BackRepoText.CheckoutPhaseTwoInstance(backRepo, &textDB)
		}
	}
}

// CopyBasicFieldsFromText
func (textDB *TextDB) CopyBasicFieldsFromText(text *models.Text) {
	// insertion point for fields commit

	textDB.Name_Data.String = text.Name
	textDB.Name_Data.Valid = true

	textDB.Content_Data.String = text.Content
	textDB.Content_Data.Valid = true

	textDB.PreserveWhiteSpace_Data.Bool = text.PreserveWhiteSpace
	textDB.PreserveWhiteSpace_Data.Valid = true
}

// CopyBasicFieldsFromTextWOP
func (textDB *TextDB) CopyBasicFieldsFromTextWOP(text *TextWOP) {
	// insertion point for fields commit

	textDB.Name_Data.String = text.Name
	textDB.Name_Data.Valid = true

	textDB.Content_Data.String = text.Content
	textDB.Content_Data.Valid = true

	textDB.PreserveWhiteSpace_Data.Bool = text.PreserveWhiteSpace
	textDB.PreserveWhiteSpace_Data.Valid = true
}

// CopyBasicFieldsToText
func (textDB *TextDB) CopyBasicFieldsToText(text *models.Text) {
	// insertion point for checkout of basic fields (back repo to stage)
	text.Name = textDB.Name_Data.String
	text.Content = textDB.Content_Data.String
	text.PreserveWhiteSpace = textDB.PreserveWhiteSpace_Data.Bool
}

// CopyBasicFieldsToTextWOP
func (textDB *TextDB) CopyBasicFieldsToTextWOP(text *TextWOP) {
	text.ID = int(textDB.ID)
	// insertion point for checkout of basic fields (back repo to stage)
	text.Name = textDB.Name_Data.String
	text.Content = textDB.Content_Data.String
	text.PreserveWhiteSpace = textDB.PreserveWhiteSpace_Data.Bool
}

// Backup generates a json file from a slice of all TextDB instances in the backrepo
func (backRepoText *BackRepoTextStruct) Backup(dirPath string) {

	filename := filepath.Join(dirPath, "TextDB.json")

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*TextDB, 0)
	for _, textDB := range backRepoText.Map_TextDBID_TextDB {
		forBackup = append(forBackup, textDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	file, err := json.MarshalIndent(forBackup, "", " ")

	if err != nil {
		log.Panic("Cannot json Text ", filename, " ", err.Error())
	}

	err = ioutil.WriteFile(filename, file, 0644)
	if err != nil {
		log.Panic("Cannot write the json Text file", err.Error())
	}
}

// Backup generates a json file from a slice of all TextDB instances in the backrepo
func (backRepoText *BackRepoTextStruct) BackupXL(file *xlsx.File) {

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*TextDB, 0)
	for _, textDB := range backRepoText.Map_TextDBID_TextDB {
		forBackup = append(forBackup, textDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	sh, err := file.AddSheet("Text")
	if err != nil {
		log.Panic("Cannot add XL file", err.Error())
	}
	_ = sh

	row := sh.AddRow()
	row.WriteSlice(&Text_Fields, -1)
	for _, textDB := range forBackup {

		var textWOP TextWOP
		textDB.CopyBasicFieldsToTextWOP(&textWOP)

		row := sh.AddRow()
		row.WriteStruct(&textWOP, -1)
	}
}

// RestoreXL from the "Text" sheet all TextDB instances
func (backRepoText *BackRepoTextStruct) RestoreXLPhaseOne(file *xlsx.File) {

	// resets the map
	BackRepoTextid_atBckpTime_newID = make(map[uint]uint)

	sh, ok := file.Sheet["Text"]
	_ = sh
	if !ok {
		log.Panic(errors.New("sheet not found"))
	}

	// log.Println("Max row is", sh.MaxRow)
	err := sh.ForEachRow(backRepoText.rowVisitorText)
	if err != nil {
		log.Panic("Err=", err)
	}
}

func (backRepoText *BackRepoTextStruct) rowVisitorText(row *xlsx.Row) error {

	log.Printf("row line %d\n", row.GetCoordinate())
	log.Println(row)

	// skip first line
	if row.GetCoordinate() > 0 {
		var textWOP TextWOP
		row.ReadStruct(&textWOP)

		// add the unmarshalled struct to the stage
		textDB := new(TextDB)
		textDB.CopyBasicFieldsFromTextWOP(&textWOP)

		textDB_ID_atBackupTime := textDB.ID
		textDB.ID = 0
		query := backRepoText.db.Create(textDB)
		if query.Error != nil {
			log.Panic(query.Error)
		}
		backRepoText.Map_TextDBID_TextDB[textDB.ID] = textDB
		BackRepoTextid_atBckpTime_newID[textDB_ID_atBackupTime] = textDB.ID
	}
	return nil
}

// RestorePhaseOne read the file "TextDB.json" in dirPath that stores an array
// of TextDB and stores it in the database
// the map BackRepoTextid_atBckpTime_newID is updated accordingly
func (backRepoText *BackRepoTextStruct) RestorePhaseOne(dirPath string) {

	// resets the map
	BackRepoTextid_atBckpTime_newID = make(map[uint]uint)

	filename := filepath.Join(dirPath, "TextDB.json")
	jsonFile, err := os.Open(filename)
	// if we os.Open returns an error then handle it
	if err != nil {
		log.Panic("Cannot restore/open the json Text file", filename, " ", err.Error())
	}

	// read our opened jsonFile as a byte array.
	byteValue, _ := ioutil.ReadAll(jsonFile)

	var forRestore []*TextDB

	err = json.Unmarshal(byteValue, &forRestore)

	// fill up Map_TextDBID_TextDB
	for _, textDB := range forRestore {

		textDB_ID_atBackupTime := textDB.ID
		textDB.ID = 0
		query := backRepoText.db.Create(textDB)
		if query.Error != nil {
			log.Panic(query.Error)
		}
		backRepoText.Map_TextDBID_TextDB[textDB.ID] = textDB
		BackRepoTextid_atBckpTime_newID[textDB_ID_atBackupTime] = textDB.ID
	}

	if err != nil {
		log.Panic("Cannot restore/unmarshall json Text file", err.Error())
	}
}

// RestorePhaseTwo uses all map BackRepo<Text>id_atBckpTime_newID
// to compute new index
func (backRepoText *BackRepoTextStruct) RestorePhaseTwo() {

	for _, textDB := range backRepoText.Map_TextDBID_TextDB {

		// next line of code is to avert unused variable compilation error
		_ = textDB

		// insertion point for reindexing pointers encoding
		// reindexing Node field
		if textDB.NodeID.Int64 != 0 {
			textDB.NodeID.Int64 = int64(BackRepoNodeid_atBckpTime_newID[uint(textDB.NodeID.Int64)])
			textDB.NodeID.Valid = true
		}

		// reindexing EnclosingRune field
		if textDB.EnclosingRuneID.Int64 != 0 {
			textDB.EnclosingRuneID.Int64 = int64(BackRepoRuneid_atBckpTime_newID[uint(textDB.EnclosingRuneID.Int64)])
			textDB.EnclosingRuneID.Valid = true
		}

		// update databse with new index encoding
		query := backRepoText.db.Model(textDB).Updates(*textDB)
		if query.Error != nil {
			log.Panic(query.Error)
		}
	}

}

// BackRepoText.ResetReversePointers commits all staged instances of Text to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoText *BackRepoTextStruct) ResetReversePointers(backRepo *BackRepoStruct) (Error error) {

	for idx, text := range backRepoText.Map_TextDBID_TextPtr {
		backRepoText.ResetReversePointersInstance(backRepo, idx, text)
	}

	return
}

func (backRepoText *BackRepoTextStruct) ResetReversePointersInstance(backRepo *BackRepoStruct, idx uint, astruct *models.Text) (Error error) {

	// fetch matching textDB
	if textDB, ok := backRepoText.Map_TextDBID_TextDB[idx]; ok {
		_ = textDB // to avoid unused variable error if there are no reverse to reset

		// insertion point for reverse pointers reset
		// end of insertion point for reverse pointers reset
	}

	return
}

// this field is used during the restauration process.
// it stores the ID at the backup time and is used for renumbering
var BackRepoTextid_atBckpTime_newID map[uint]uint
