// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional, Input } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { ActivatedRoute, Router, RouterState } from '@angular/router';
import { ParagraphStyleDB } from '../paragraphstyle-db'
import { ParagraphStyleService } from '../paragraphstyle.service'

// insertion point for additional imports

import { RouteService } from '../route-service';

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-paragraphstylestable',
  templateUrl: './paragraphstyles-table.component.html',
  styleUrls: ['./paragraphstyles-table.component.css'],
})
export class ParagraphStylesTableComponent implements OnInit {

  @Input() GONG__StackPath: string = ""

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of ParagraphStyle instances
  selection: SelectionModel<ParagraphStyleDB> = new (SelectionModel)
  initialSelection = new Array<ParagraphStyleDB>()

  // the data source for the table
  paragraphstyles: ParagraphStyleDB[] = []
  matTableDataSource: MatTableDataSource<ParagraphStyleDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.paragraphstyles
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (paragraphstyleDB: ParagraphStyleDB, property: string) => {
      switch (property) {
        case 'ID':
          return paragraphstyleDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return paragraphstyleDB.Name;

        case 'Node':
          return (paragraphstyleDB.Node ? paragraphstyleDB.Node.Name : '');

        case 'Content':
          return paragraphstyleDB.Content;

        case 'ValAttr':
          return paragraphstyleDB.ValAttr;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (paragraphstyleDB: ParagraphStyleDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the paragraphstyleDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += paragraphstyleDB.Name.toLowerCase()
      if (paragraphstyleDB.Node) {
        mergedContent += paragraphstyleDB.Node.Name.toLowerCase()
      }
      mergedContent += paragraphstyleDB.Content.toLowerCase()
      mergedContent += paragraphstyleDB.ValAttr.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private paragraphstyleService: ParagraphStyleService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of paragraphstyle instances
    public dialogRef: MatDialogRef<ParagraphStylesTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
    private activatedRoute: ActivatedRoute,

    private routeService: RouteService,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      this.GONG__StackPath = dialogData.GONG__StackPath
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.paragraphstyleService.ParagraphStyleServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getParagraphStyles()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Delete', // insertion point for columns to display
        "Name",
        "Node",
        "Content",
        "ValAttr",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Node",
        "Content",
        "ValAttr",
      ]
      this.selection = new SelectionModel<ParagraphStyleDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    let stackPath = this.activatedRoute.snapshot.paramMap.get('GONG__StackPath')
    if (stackPath != undefined) {
      this.GONG__StackPath = stackPath
    }

    this.getParagraphStyles()

    this.matTableDataSource = new MatTableDataSource(this.paragraphstyles)
  }

  getParagraphStyles(): void {
    this.frontRepoService.pull(this.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.paragraphstyles = this.frontRepo.ParagraphStyles_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let paragraphstyle of this.paragraphstyles) {
            let ID = this.dialogData.ID
            let revPointer = paragraphstyle[this.dialogData.ReversePointer as keyof ParagraphStyleDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(paragraphstyle)
            }
            this.selection = new SelectionModel<ParagraphStyleDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, ParagraphStyleDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          // we associates on sourceInstance of type SourceStruct with a MANY MANY associations to ParagraphStyleDB
          // the field name is sourceField
          let sourceFieldArray = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as ParagraphStyleDB[]
          if (sourceFieldArray != null) {
            for (let associationInstance of sourceFieldArray) {
              let paragraphstyle = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as ParagraphStyleDB
              this.initialSelection.push(paragraphstyle)
            }
          }

          this.selection = new SelectionModel<ParagraphStyleDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.paragraphstyles
      }
    )
  }

  // newParagraphStyle initiate a new paragraphstyle
  // create a new ParagraphStyle objet
  newParagraphStyle() {
  }

  deleteParagraphStyle(paragraphstyleID: number, paragraphstyle: ParagraphStyleDB) {
    // list of paragraphstyles is truncated of paragraphstyle before the delete
    this.paragraphstyles = this.paragraphstyles.filter(h => h !== paragraphstyle);

    this.paragraphstyleService.deleteParagraphStyle(paragraphstyleID, this.GONG__StackPath).subscribe(
      paragraphstyle => {
        this.paragraphstyleService.ParagraphStyleServiceChanged.next("delete")
      }
    );
  }

  editParagraphStyle(paragraphstyleID: number, paragraphstyle: ParagraphStyleDB) {

  }

  // set editor outlet
  setEditorRouterOutlet(paragraphstyleID: number) {
    let outletName = this.routeService.getEditorOutlet(this.GONG__StackPath)
    let fullPath = this.routeService.getPathRoot() + "-" + "paragraphstyle" + "-detail"

    let outletConf: any = {}
    outletConf[outletName] = [fullPath, paragraphstyleID, this.GONG__StackPath]

    this.router.navigate([{ outlets: outletConf }])
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.paragraphstyles.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.paragraphstyles.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<ParagraphStyleDB>()

      // reset all initial selection of paragraphstyle that belong to paragraphstyle
      for (let paragraphstyle of this.initialSelection) {
        let index = paragraphstyle[this.dialogData.ReversePointer as keyof ParagraphStyleDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(paragraphstyle)

      }

      // from selection, set paragraphstyle that belong to paragraphstyle
      for (let paragraphstyle of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = paragraphstyle[this.dialogData.ReversePointer as keyof ParagraphStyleDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(paragraphstyle)
      }


      // update all paragraphstyle (only update selection & initial selection)
      for (let paragraphstyle of toUpdate) {
        this.paragraphstyleService.updateParagraphStyle(paragraphstyle, this.GONG__StackPath)
          .subscribe(paragraphstyle => {
            this.paragraphstyleService.ParagraphStyleServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, ParagraphStyleDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedParagraphStyle = new Set<number>()
      for (let paragraphstyle of this.initialSelection) {
        if (this.selection.selected.includes(paragraphstyle)) {
          // console.log("paragraphstyle " + paragraphstyle.Name + " is still selected")
        } else {
          console.log("paragraphstyle " + paragraphstyle.Name + " has been unselected")
          unselectedParagraphStyle.add(paragraphstyle.ID)
          console.log("is unselected " + unselectedParagraphStyle.has(paragraphstyle.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let paragraphstyle = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as ParagraphStyleDB
      if (unselectedParagraphStyle.has(paragraphstyle.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<ParagraphStyleDB>) = new Array<ParagraphStyleDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          paragraphstyle => {
            if (!this.initialSelection.includes(paragraphstyle)) {
              // console.log("paragraphstyle " + paragraphstyle.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + paragraphstyle.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = paragraphstyle.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = paragraphstyle.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("paragraphstyle " + paragraphstyle.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<ParagraphStyleDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
